import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  let str = '``` json {\'code\': \'mixedPlay([{"channelId": 1, "time": 20000}, {"channelId": 4, "time": 20000}, {"channelId": 6, "time": 20000}]);\',\'description\': \'正在为您混合播放“枕边蜜语”，“浓情可可”以及“精神满满”三种香氛，各自持续20秒。这三种香味的组合会让您感到新奇且轻松。\',\'remark\': \'为了达到最佳效果，我们建议您在空气流通的环境中使用。\'}```';

  let response = '明白了，根据你的设备香氛胶囊改变，我们现在将选择播放薄荷香氛，因为薄荷气味通常可以使人感到精神饱满。这是 JSON 格式的输出结果：``` json{"code": "mixedPlay([{\'channelId\': 6, \'time\': 60000}])","description": "精神满满","remark": "正在为您播放精神满满的薄荷香氛，持续时间60秒，以帮助提神驾驶。"}```这样，声音播报就可以根据描叙remark字段，来给予用户适当的信息反馈。';

  console.log(response)

  let jsonMatch = response.match(/```([\s\S]*?)```/)

  console.log(jsonMatch)

  // console.log(str)
  let strIndex = str.indexOf('{')
  let endIndex = str.lastIndexOf('}')

  // console.log(str.substring(strIndex, endIndex + 1))

  //
  // // let str = '{\'code\': \'mixedPlay([{"channelId": 1, "time": 20000}, {"channelId": 4, "time": 20000}, {"channelId": 6, "time": 20000}]);\',\'description\': \'正在为您混合播放“枕边蜜语”，“浓情可可”以及“精神满满”三种香氛，各自持续20秒。这三种香味的组合会让您感到新奇且轻松。\',\'remark\': \'为了达到最佳效果，我们建议您在空气流通的环境中使用。\'}';
  //
  // let replaced1 = str.replace(/'/g, '"')
  //   .replace(/'code'/g, `"code"`)
  //   .replace(/"channelId"/g, `'channelId'`)
  //   .replace(/"time"/g, `'time'`);
  // console.log(replaced1)
  //
  // function parseFlexibleJSON(jsonString) {
  //   try {
  //     return JSON.parse(jsonString);
  //   } catch (e) {
  //     let replaced = jsonString.replace(/'/g, '"');
  //     // console.log(replaced)
  //     // return JSON.parse(replaced);
  //   }
  // }
  //
  // console.log(parseFlexibleJSON(replaced1))

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Scentrealm AI.
          </p>
          <div>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}></div>
      </main>
    </>
  )
}
