import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  let str = '男士通常喜欢清新的味道，其中咖啡、玫瑰和薄荷都是不错的选择。这里我们选择薄荷气味，清新同时也有提神醒脑的效果。以下是对应的函数调用和JSON格式的输出结果：{"code": "mixedPlay([{\"channelId\": 6, \"time\": 60000}]);","description": "正在播放薄荷香氛，持续时间60秒，以帮助您保持清新和精神饱满。","remark": "这是一款男士喜欢的香氛，非常清新也适用于工作和驾驶。"}';


  let jsonMatch = str.match(/{([\s\S]*?)\"}/)

  console.log(jsonMatch[jsonMatch.length - 1])
  let strIndex = str.indexOf('{')
  let endIndex = str.lastIndexOf('}')

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Scentrealm AI.
          </p>
          <div>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}></div>
      </main>
    </>
  )
}
