import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  let str = `确实，您对应的香氛胶囊和产品名字都与杭州的特色紧密相关。当我们谈到杭州，龙井茶和荷花是几乎立即浮现在脑海中的图像。下面的代码会将这两种香氛同时播放，模拟一个您所描述的 "杭州乐园”的气氛。\n{\n"code": "mixedPlay([{'channelId': 1, 'time': 60000}, {'channelId': 4, 'time': 60000}]);",\n"description": "正在播放 '荷花' 和 '龙井' 的香氛，每种各持续60秒。",\n"remark": "这将创造出一种仿佛身在杭州的气氛。"\n}`;

  // console.log(str);
  let jsonMatch = str.match(/{([\s\S]*?)\"}/)

  console.log(jsonMatch)
  let strIndex = str.indexOf('{')
  let endIndex = str.lastIndexOf('}')

  // useEffect(() => {
  //   const eventSource = new EventSource('/api/sse');
  //
  //   eventSource.addEventListener('chat', (event) => {
  //     console.log(event.data);
  //   });
  //
  //   return () => {
  //     eventSource.close();
  //   }
  // }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Scentrealm AI.
          </p>
          <div>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}></div>
      </main>
    </>
  )
}
